complete -c ipic -xo a -d 'Search for an album'
complete -c ipic -xo b -d 'Search for a book'
complete -c ipic -xo f -d 'Search for a film'
complete -c ipic -fo h -d 'Show help'
complete -c ipic -xo i -d 'Search for an iOS app'
complete -c ipic -xo m -d 'Search for a macOS app'
complete -c ipic -xo t -d 'Search for a TV show'
